[app]
title = Smart Calculator
package.name = smartcalculator
package.domain = org.calculator
source.dir = .
source.main = main.py
version = 1.0.0
requirements = python3,kivy==2.1.0
android.minapi = 21
android.targetapi = 34
android.ndk = 25b
android.sdk = 33
android.accept_sdk_license = true
android.ndk_api = 21
android.arch = armeabi-v7a
android.allow_backup = true
android.icon = 
android.orientation = portrait
android.permissions = 
android.wakelock = false
android.meta_data = 
android.manifest.intent_filters = 
android.gradle_dependencies = 
android.add_src = 
android.add_res = 
android.add_aars = 
android.add_jars = 
android.add_manifest = 
android.add_activities = 
android.add_libs_armeabi_v7a = 
android.add_libs_arm64_v8a = 
android.add_libs_x86 = 
android.add_libs_x86_64 = 
android.add_frameworks = 
android.add_java_files = 
android.add_aidl_files = 
android.entrypoint = org.kivy.android.PythonActivity
android.billing_service = 
android.google_play_services = 
android.billing_key = 
android.archs = armeabi-v7a
android.no-compile-pattern = 
android.ignore-path-pattern = 
android.disable_androidx = false
android.enable_androidx = true
android.gradle_options = 
android.private_storage = true
android.logcat_filters = *:S python:D
android.early_config = 
android.manifest_placeholders = 
android.manifest_application_arguments = 
android.extra_manifest_xml = 
android.extra_manifest_application_xml = 
android.extra_manifest_application_arguments = 
android.force_debug = false
android.force_release = false
android.force_ndk_debug = false
android.force_ndk_release = false
android.force_sdk_debug = false
android.force_sdk_release = false
android.force_gradle_debug = false
android.force_gradle_release = false
android.force_aapt_debug = false
android.force_aapt_release = false
android.force_dx_debug = false
android.force_dx_release = false
android.force_zipalign_debug = false
android.force_zipalign_release = false
android.force_apksigner_debug = false
android.force_apksigner_release = false
android.force_apk_debug = false
android.force_apk_release = false
android.force_jarsigner_debug = false
android.force_jarsigner_release = false
android.force_bundle_debug = false
android.force_bundle_release = false
android.force_split_debug = false
android.force_split_release = false
android.force_assemble_debug = false
android.force_assemble_release = false
android.force_process_resources_debug = false
android.force_process_resources_release = false
android.force_compile_debug = false
android.force_compile_release = false
android.force_link_debug = false
android.force_link_release = false
android.force_strip_debug = false
android.force_strip_release = false
android.force_merge_assets_debug = false
android.force_merge_assets_release = false
android.force_merge_jni_debug = false
android.force_merge_jni_release = false
android.force_merge_libs_debug = false
android.force_merge_libs_release = false
android.force_merge_res_debug = false
android.force_merge_res_release = false
android.force_merge_so_debug = false
android.force_merge_so_release = false
android.force_merge_xml_debug = false
android.force_merge_xml_release = false